# Generated by Django 2.1.7 on 2019-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190311_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogproject',
            name='blog_link',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='digitalproject',
            name='blog_link',
            field=models.CharField(default='', max_length=140),
        ),
    ]
