# Generated by Django 2.0.6 on 2018-07-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180713_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content3',
            new_name='body',
        ),
    ]
