# Generated by Django 2.0.6 on 2018-08-31 22:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180831_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
